# -*- mode: python ; coding: utf-8 -*-

# 本文件用于打包 Windows 程序
# pip install pyinstaller
# pyinstaller --clean --noconfirm build_exe.spec

block_cipher = None


a = Analysis(['main.py'],
             pathex=['.'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=['./lanzou/gui/login_assister.py','PyQtWebEngine', ],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

a.binaries = [x for x in a.binaries if 'login_assister' not in x[0]]
print(a.binaries)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='lanzou-gui',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False,
          version='./version_info.txt',
          icon='./app_icon.ico')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[
                    'qt5webenginecore.dll',
                    'vcruntime140.dll',
                    'vcruntime140_1.dll',
                    'msvcp140_1.dll','msvcp140.dll',
                    'qtquick3deffectplugin.dll',
                    'qtgraphicaleffectsprivate.dll',
                    'qtquick2plugin.dll',
                    'declarative_nfc.dll',
                    'modelsplugin.dll',
                    'qtquickextrasflatplugin.dll',
                    'dialogplugin.dll',
                    'qtquickscene2dplugin.dll',
                    'sharedimageplugin.dll',
                    'qtquick3dhelpersplugin.dll',
                    'qmlsettingsplugin.dll',
                    'qmlwavefrontmeshplugin.dll',
                    'qxdgdesktopportal.dll',
                    'qtquicktemplates2plugin.dll',
                    'qtquicktimelineplugin.dll',
                    'locationlabsplugin.dll',
                    'qquicklayoutsplugin.dll',
                    'qico.dll',
                    'declarative_positioning.dll',
                    'qtlabscalendarplugin.dll',
                    'qsvg.dll',
                    'qmlplugin.dll',
                    'qtquickcontrols2fusionstyleplugin.dll',
                    'qtiff.dll',
                    'qtqmlremoteobjects.dll',
                    'qtwebengineplugin.dll',
                    'qtquickcontrols2plugin.dll',
                    'declarative_qmlwebsockets.dll',
                    'declarative_sensors.dll',
                    'qsvgicon.dll',
                    'qmltestplugin.dll',
                    'declarative_location.dll',
                    'dialogsprivateplugin.dll',
                    'declarative_multimedia.dll',
                    'windowplugin.dll',
                    'particlesplugin.dll',
                    'qtgraphicaleffectsplugin.dll',
                    'workerscriptplugin.dll',
                    'qgif.dll',
                    'qtquickcontrolsplugin.dll',
                    'qminimal.dll',
                    'qjpeg.dll',
                    'qwebgl.dll',
                    'qtqmlstatemachine.dll',
                    'qtquickcontrols2materialstyleplugin.dll',
                    'qgenericbearer.dll',
                    'declarative_webchannel.dll',
                    'labsanimationplugin.dll',
                    'qwbmp.dll',
                    'qtquickcontrols2imaginestyleplugin.dll',
                    'qtquickcontrols2universalstyleplugin.dll',
                    'qmlshapesplugin.dll',
                    'qtposition_serialnmea.dll',
                    'qtquickscene3dplugin.dll',
                    'qmllocalstorageplugin.dll',
                    'qtquick3dmaterialplugin.dll',
                    'qmlxmllistmodelplugin.dll',
                    'qtposition_positionpoll.dll',
                    'qmlfolderlistmodelplugin.dll',
                    'qtquickextrasplugin.dll',
                    'windowsprintersupport.dll',
                    'labsmodelsplugin.dll',
                    'qtposition_winrt.dll',
                    'qtga.dll',
                    'qwindowsvistastyle.dll',
                    'qwebp.dll',
                    'qwindows.dll',
                    'qtlabsplatformplugin.dll',
                    'declarative_bluetooth.dll',
                    'qoffscreen.dll',
                    'widgetsplugin.dll',
                    'qicns.dll',
                    'qquick3dplugin.dll'
                ],
               name='lanzou-gui')
